add unbind to enable runtime binding/unbinding
rpclib/rpclib pull request #301
Opened 2022-05-14 06:34 UTC by jaafari

adding unbind function to remove a binding in runtime (if wanted) and names function to list all binded functors (usable for debugging etc.)

2022-05-14 17:08 UTC, qchateau requested changes
Thank you for your contribution. I left a few comments

2022-05-14 17:08 UTC, qchateau commented on include/rpc/dispatcher.h
> +	void remove(std::string const &name) {
Any reason for naming this remove instead of unbind ?
Also, you could return a boolean telling the caller whether something was erased or not ?

2022-05-14 17:08 UTC, qchateau commented on include/rpc/dispatcher.h
> +	std::vector<std::string> names() {
this method should be const

2022-05-14 17:08 UTC, qchateau commented on include/rpc/server.h
> +    std::vector<std::string> names() {
method should be const

2022-05-15 06:32 UTC, jaafari commented
thanks, changes applied.

2022-05-15 08:33 UTC, merged